# Generated by Django 4.0.1 on 2023-06-14 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cate_num', models.IntegerField(primary_key=True, serialize=False)),
                ('cate_name', models.CharField(max_length=100)),
                ('cate_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'category',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Provision',
            fields=[
                ('pro_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('pro_name', models.CharField(max_length=20)),
                ('pro_content', models.CharField(max_length=2000)),
                ('pro_essential', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'provision',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=20)),
                ('user_email', models.CharField(max_length=20)),
                ('user_pass', models.CharField(max_length=20)),
                ('user_phon', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'user_',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User_service',
            fields=[
                ('user_ser_num', models.IntegerField(primary_key=True, serialize=False)),
                ('user_create', models.DateTimeField(auto_now_add=True)),
                ('user_pass_modified', models.DateTimeField(auto_now=True)),
                ('user_login_date', models.DateTimeField(auto_now=True)),
                ('user_count', models.IntegerField()),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, to='mainapp.user')),
            ],
            options={
                'db_table': 'user_img',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User_img',
            fields=[
                ('user_num', models.IntegerField(primary_key=True, serialize=False)),
                ('user_path', models.CharField(max_length=100)),
                ('user_date', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, to='mainapp.user')),
            ],
            options={
                'db_table': 'user_img',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Provision_history',
            fields=[
                ('his_num', models.IntegerField(primary_key=True, serialize=False)),
                ('his_consent', models.CharField(max_length=1)),
                ('his_date', models.DateTimeField(auto_now_add=True)),
                ('pro_code', models.ForeignKey(db_column='pro_code', on_delete=django.db.models.deletion.PROTECT, to='mainapp.provision')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, to='mainapp.user')),
            ],
            options={
                'db_table': 'provisionhistory',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='provision',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, to='mainapp.user'),
        ),
        migrations.CreateModel(
            name='Naver_account',
            fields=[
                ('naver_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('naver_token', models.CharField(max_length=255)),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, to='mainapp.user')),
            ],
            options={
                'db_table': 'naver_account',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Kakao_account',
            fields=[
                ('kakao_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('kakao_token', models.CharField(max_length=255)),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, to='mainapp.user')),
            ],
            options={
                'db_table': 'kakao_account',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='google_account',
            fields=[
                ('google_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('google_token', models.CharField(max_length=255)),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, to='mainapp.user')),
            ],
            options={
                'db_table': 'google_account',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('com_num', models.IntegerField(primary_key=True, serialize=False)),
                ('com_title', models.CharField(max_length=255)),
                ('com_content', models.TextField()),
                ('com_combool', models.CharField(max_length=1)),
                ('com_date', models.DateTimeField(auto_now_add=True)),
                ('com_count', models.IntegerField()),
                ('com_path', models.CharField(max_length=100)),
                ('cate_num', models.ForeignKey(db_column='cate_num', on_delete=django.db.models.deletion.PROTECT, to='mainapp.category')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, to='mainapp.user')),
            ],
            options={
                'db_table': 'community',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_num', models.IntegerField(primary_key=True, serialize=False)),
                ('comment_content', models.TextField()),
                ('comment_create_date', models.DateTimeField(auto_now_add=True)),
                ('comment_modified_date', models.DateTimeField(auto_now=True)),
                ('com_num', models.ForeignKey(db_column='com_num', on_delete=django.db.models.deletion.PROTECT, to='mainapp.community')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, to='mainapp.user')),
            ],
            options={
                'db_table': 'comment',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='category',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, to='mainapp.user'),
        ),
    ]
